# https://docs.astral.sh/uv/guides/integration/github/#setting-up-python
name: Tests

on:
 push

jobs:

  python:
    name: python tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"

    steps:
      - uses: actions/checkout@v4
      - name: Install pixi
        uses: prefix-dev/setup-pixi@v0.8.14
        with:
          pixi-version: v0.46.0
          cache: true

      # - name: Install the project
      #   run: pixi install

      - name: Build the package
        run: pixi run mojo package pixi_mojo_experiments

      - name: Run tests
        run: pixi run mojo test -I . test
